app = "openarti-web"
primary_region = "nrt"

[build]
  dockerfile = "../docker/Dockerfile.web"

[env]
  OPENARTI_API_URL = "https://openarti-api.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
